---
all:
  hosts:
    openstack:
      ansible_host: 'insert.host.ip.here'
      ansible_user: deploy
      ansible_become: yes
      ansible_become_pass: "{{vault_ansible_become_pass}}"
      ansible_ssh_pass: "{{vault_ansible_become_pass}}"
