---
- name: Deploy OVS cfg file
  template:
    src: ifcfg-br-ex.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-br-ex
- name: Deploy eth dev cfg file
  template:
    src: ifcfg-eth.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-eth0
- name: Restart network
  service:
    name: network
    state: restarted
